# Generated by Django 3.0.5 on 2020-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200929_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
