# Generated by Django 3.0.5 on 2020-10-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200929_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='events',
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='athletes',
            field=models.ManyToManyField(related_name='athlete_list', through='events.Participation', to='events.Athlete'),
        ),
    ]
