# Generated by Django 3.0.5 on 2020-10-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201003_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='athletes',
        ),
        migrations.AddField(
            model_name='event',
            name='athletes',
            field=models.ManyToManyField(related_name='athlete_list', through='events.Participation', to='events.Athlete'),
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Athlete')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Country')),
            ],
        ),
    ]
