# Generated by Django 3.0.5 on 2020-10-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201003_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Country'),
        ),
    ]
